Presentation/DesignSystem/Sources/Font.swift

[PC-211](https://yapp25app3.atlassian.net/browse/PC-211)
- 디자인시스템 변경사항 반영했습니다.
-  새로운 폰트 케이스`body_S_R` 추가
- `body_S_SB `, `body_S_M`, `body_S_R`의 Line height를 18에서 20으로 수정
- 확인 후 Approve 부탁드려요!! 
[PC-211]: https://yapp25app3.atlassian.net/browse/PC-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-211] Fix: Change font line heights in design system

---

Tuist/ProjectDescriptionHelpers/AppContants.swift
Tuist/ProjectDescriptionHelpers/Project/Project+app.swift

[PC-296](https://yapp25app3.atlassian.net/browse/PC-296)
- 앱 타겟 번들ID `com.piece.puzzly`로 변경
- 앱 organizationName `puzzly`로 변경
- 특이사항 없어서 빌드 한번 해보시고 빌드 잘 되면 바로 approve 해주시면 될거같습니다~
| 화면 이름 |
| :--: |
|  |
[PC-296]: https://yapp25app3.atlassian.net/browse/PC-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-296] 앱 bundleId, organizationName 수정

---

App/Sources/ContentView.swift
Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/MatchProfileBasicView.swift
Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickView.swift
Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkView.swift

[PC-450](https://yapp25app3.atlassian.net/browse/PC-450)
- 큰 변경사항은 없어 머지합니다.
| 화면 이름 |
| :--: |
|  |
[PC-450]: https://yapp25app3.atlassian.net/browse/PC-450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-450] Fix: 기본 내비게이션바 hidden 처리

---

Data/DTO/Sources/SignUp/ValueTalksResponseDTO.swift
Data/PCNetwork/Sources/Endpoint/ValueTalksEndpoint.swift
Data/Repository/Sources/RepositoryFactory.swift
Data/Repository/Sources/ValueTalks/ValueTalksRepository.swift
Domain/RepositoryInterfaces/Sources/ValueTalks/ValueTalksRepositoryInterface.swift
Domain/UseCases/Sources/Profile/GetValueTalksUseCase.swift
Domain/UseCases/Sources/UseCaseFactory.swift
Presentation/Coordinator/Sources/Coordinator.swift
Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerView.swift
Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerViewModel.swift
Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/TextCountIndicator.swift
Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkCard.swift
Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkView.swift
Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkViewModel.swift
Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ViewTalkCardViewModel.swift
Presentation/Feature/SignUp/Sources/SignUpViewFactory.swift

[PC-502](https://yapp25app3.atlassian.net/browse/PC-502)
- 프로필 생성 - 가치관 Talk 입력 기능 구현
- 피그마에 별도 Validation 정책이 없어 우선은 입력값이 없어도 다음으로 넘어갈 수 있도록 구현하였습니다.
- TextEditor의 커서 색상 변경을 기본적으로 지원하지 않아서, 일단은 빠른 출시를 위해 기본 색상으로 구현하였습니다.
- 
| 화면 이름 |
| :--: |
|  |
[PC-502]: https://yapp25app3.atlassian.net/browse/PC-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-502] Feat: 프로필 생성 - 가치관 Talk 기능 구현

---

Data/DTO/Sources/SignUp/ValuePicksResponseDTO.swift
Data/PCNetwork/Sources/Endpoint/ValuePicksEndpoint.swift
Data/Repository/Sources/RepositoryFactory.swift
Data/Repository/Sources/ValuePicks/ValuePicksRepository.swift
Domain/RepositoryInterfaces/Sources/ValuePicksRepositoryInterface/ValuePicksRepositoryInterface.swift
Domain/UseCases/Sources/Profile/GetProfileUseCase.swift
Domain/UseCases/Sources/Profile/GetValuePicksUseCase.swift
Domain/UseCases/Sources/UseCaseFactory.swift
Presentation/Coordinator/Sources/Coordinator.swift
Presentation/DesignSystem/Sources/PCToast.swift
Presentation/DesignSystem/Sources/SelectCard.swift
Presentation/Feature/Home/Sources/HomeView.swift
Presentation/Feature/Profile/Sources/ProfileView.swift
Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerView.swift
Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerViewModel.swift
Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickCard.swift
Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickCardViewModel.swift
Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickView.swift
Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickViewModel.swift
Presentation/Feature/SignUp/Sources/SignUpViewFactory.swift
Presentation/Router/Sources/Route.swift

[PC-503](https://yapp25app3.atlassian.net/browse/PC-503)
- 프로필 생성 - 가치관 Pick 입력 화면 구현
- 선택하지 않은 문항이 있을 시에 대한 validation 로직 포함
- `SelectCard` 컴포넌트에 `isEditing` 매개변수 추가
- `PCToast` 컴포넌트 구현
- 
| 화면 이름 |
| :--: |
|  |
[PC-503]: https://yapp25app3.atlassian.net/browse/PC-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-503] 프로필 생성 - 가치관Pick 입력 구현

---

Presentation/Feature/MatchingMain/Project.swift
Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift

[PC-567](https://yapp25app3.atlassian.net/browse/PC-567)
-  매칭 메인에서 매칭 상세로 진입 구현
- 서우님 매칭 메인 화면에서 버튼 액션 처리할 때 제가 작성한 주석 참고하세용!!
| 화면 이름 |
| :--: |
|  |
[PC-567]: https://yapp25app3.atlassian.net/browse/PC-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-567] Feat: 매칭 메인에서 매칭 상세로 진입 구현

---

Data/LocalStorage/Sources/UserDefaults/PCUserDefaults.swift
Data/LocalStorage/Sources/UserDefaults/PCUserDefaultsService.swift
Data/LocalStorage/Sources/UserDefaults/UserDefaultsKeys.swift

[PC-586](https://yapp25app3.atlassian.net/browse/PC-586)
- UserDefaults를 사용하기 위한 객체와 key 세팅
- 회원가입 화면에서 권한 설정 시 UserDefaults에도 저장하도록 해주세요
| 화면 이름 |
| :--: |
|  |
[PC-586]: https://yapp25app3.atlassian.net/browse/PC-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-586] UserDefaults 구현

---

Data/PCNetwork/Sources/Endpoint/LoginEndpoint.swift

[PC-](https://yapp25app3.atlassian.net/browse/PC-)
- 작업 내용
- ㅇㅇㅇㅇ
| 화면 이름 |
| :--: |
|  |

[PC-000] Fix: Endpoint.swift 파일 컴파일 오류 수정

---

Data/PCNetwork/Sources/Endpoint/LoginEndpoint.swift
Data/PCNetwork/Sources/Endpoint/MatchesEndpoint.swift
Data/PCNetwork/Sources/Endpoint/ProfileEndpoint.swift
Data/PCNetwork/Sources/Endpoint/ReportsEndpoint.swift
Data/PCNetwork/Sources/Endpoint/SSEEndpoint.swift

[PC-](https://yapp25app3.atlassian.net/browse/PC-)
- 작업 내용
- ㅇㅇㅇㅇ
| 화면 이름 |
| :--: |
|  |

[PC-633] Feat: Endpoint Header 값 추가

---

App/Sources/PieceApp.swift
Tuist/ProjectDescriptionHelpers/Project/Project+app.swift

[PC-](https://yapp25app3.atlassian.net/browse/PC-)
- 작업 내용
- ㅇㅇㅇㅇ
| 화면 이름 |
| :--: |
|  |

[PC-633] Fix: 카카오톡 앱으로 로그인 에러 해결

---

Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift
Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift

[PC-679](https://yapp25app3.atlassian.net/browse/PC-679)
- 작업 내용
- ㅇㅇㅇㅇ
| 화면 이름 |
| :--: |
|  |
[PC-679]: https://yapp25app3.atlassian.net/browse/PC-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-679] Fix: 프로필 생성 시, 텍스트필드 Focus 미작동 및 BottomSheet 기타 custom String 누락 해결 

---

Data/DTO/Sources/UserRoleResponseDTO.swift
Data/PCNetwork/Sources/Endpoint/CommonEndpoint.swift
Data/Repository/Sources/Common/CommonRepository.swift
Domain/Entities/Sources/UserRoleModel.swift
Domain/RepositoryInterfaces/Sources/Common/CommonRepositoryInterface.swift
Domain/UseCases/Sources/Common/GetUserRoleUseCase.swift
Domain/UseCases/Sources/UseCaseFactory.swift

[PC-](https://yapp25app3.atlassian.net/browse/PC-)
- 작업 내용
- ㅇㅇㅇㅇ
- 여러 화면에서 공통으로 사용하기 위한 User Role을 확인하는 UseCase를 생성했습니다
| 화면 이름 |
| :--: |
|  |

[PC-000] Feat: User Role 확인 Common UseCase 생성

---

Data/DTO/Sources/Login/TokenRefreshRequestDTO.swift
Data/DTO/Sources/Login/TokenRefreshResponseDTO.swift
Data/PCNetwork/Sources/APIRequestInterceptor.swift
Data/PCNetwork/Sources/Endpoint/LoginEndpoint.swift
Domain/Entities/Sources/User/UserRole.swift
Domain/RepositoryInterfaces/Sources/Common/UserRepositoryInterface.swift
Presentation/Coordinator/Sources/Coordinator.swift
Presentation/Feature/Splash/Sources/SplashView.swift
Presentation/Feature/Splash/Sources/SplashViewFactory.swift
Presentation/Feature/Splash/Sources/SplashViewModel.swift

[PC-668](https://yapp25app3.atlassian.net/browse/PC-668)
- 서버에서 사용자의 `role`을 받아와서 분기처리 하는 로직 추가
-
| 화면 이름 |
| :--: |
|  |
[PC-668]: https://yapp25app3.atlassian.net/browse/PC-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-668] Splash 화면에서 사용자 정보를 확인하여 분기처리하는 로직 구현

---

App/Sources/AppDelegate.swift
Data/DTO/Sources/Login/FCMTokenRequestDTO.swift
Data/PCNetwork/Sources/Endpoint/LoginEndpoint.swift
Data/Repository/Sources/Login/LoginRepository.swift
Data/Repository/Sources/RepositoryFactory.swift
Domain/RepositoryInterfaces/Sources/Login/LoginRepositoryInterface.swift
Domain/UseCases/Sources/Login/CheckTokenHealthUseCase.swift
Domain/UseCases/Sources/Login/RegisterFcmTokenUseCase.swift
Domain/UseCases/Sources/Login/SendSMSCodeUseCase.swift
Domain/UseCases/Sources/Login/SocialLoginUseCase.swift
Domain/UseCases/Sources/Login/VerifySMSCodeUseCase.swift
Domain/UseCases/Sources/UseCaseFactory.swift
Utility/PCFirebase/Project.swift
Utility/PCFirebase/Sources/PCNotificationService.swift

[PC-705](https://yapp25app3.atlassian.net/browse/PC-705)
- 서버에 FCM 토큰을 등록하는 기능 구현
- `LoginRepositoryInterfaces`로 되어있는 프로토콜명에서 `s` 제거
- 
| 화면 이름 |
| :--: |
|  |
[PC-705]: https://yapp25app3.atlassian.net/browse/PC-705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-705] Feat: 서버에 FCM 토큰을 등록하는 기능 구현

---

Data/LocalStorage/Sources/Keychain/PCKeychain.swift
Data/PCNetwork/Sources/Endpoint/SettingsEndpoint.swift
Data/Repository/Sources/Settings/SettingsRepository.swift
Domain/RepositoryInterfaces/Sources/Settings/SettingsRepositoryInterface.swift
Domain/UseCases/Sources/Settings/PatchLogoutUseCase.swift
Domain/UseCases/Sources/UseCaseFactory.swift
Presentation/Coordinator/Sources/Coordinator.swift
Presentation/Feature/Home/Sources/HomeView.swift
Presentation/Feature/Home/Sources/HomeViewFactory.swift
Presentation/Feature/Home/Sources/HomeViewModel.swift
Presentation/Feature/Login/Sources/Login/LoginViewModel.swift
Presentation/Feature/Login/Sources/VerifingContact/VerifingContactViewModel.swift
Presentation/Feature/Settings/Sources/SettingsView.swift
Presentation/Feature/Settings/Sources/SettingsViewFactory.swift
Presentation/Feature/Settings/Sources/SettingsViewModel.swift

[PC-494](https://yapp25app3.atlassian.net/browse/PC-494)
- 로그아웃 api를 추가했습니다
| 화면 이름 |
| :--: |
|  |
[PC-494]: https://yapp25app3.atlassian.net/browse/PC-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-494] Feat: 유저는 설정 탭에서 로그아웃을 할 수 있다

---

Presentation/Coordinator/Sources/Coordinator.swift
Presentation/Feature/Home/Sources/HomeView.swift
Presentation/Feature/Home/Sources/HomeViewFactory.swift
Presentation/Feature/Home/Sources/HomeViewModel.swift
Presentation/Feature/Login/Sources/Login/LoginView.swift
Presentation/Feature/Login/Sources/Login/LoginViewModel.swift
Presentation/Feature/MatchingMain/Sources/MatchMainViewFactory.swift
Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
Presentation/Router/Sources/Route.swift

[PC-497](https://yapp25app3.atlassian.net/browse/PC-497)
- 사용자 Role과 매칭상태(StatusCode)값에 따라 화면 분기처리했습니다
- Login 시 이미 가입한 사용자와 아닌 사용자에 대해 분기처리했습니다.
| 화면 이름 |
| :--: |
|  |
[PC-497]: https://yapp25app3.atlassian.net/browse/PC-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-497] Feat: 매칭 화면 분기처리

---

Presentation/Feature/SignUp/Sources/AvoidContactsGuide/AvoidContactsGuideView.swift
Presentation/Feature/SignUp/Sources/PermissionRequest/PermissionRequestView.swift

[PC-767](https://yapp25app3.atlassian.net/browse/PC-767)
- 네비게이션바 레이아웃 수정
| 화면 이름 | 화면 이름 |
| ![image](https://github.com/user-attachments/assets/fa779e11-0a6f-4481-a7cf-fd7400282b5c) | ![image](https://github.com/user-attachments/assets/129f5238-343d-4504-a2bc-bab2b9b0c4d7) |
[PC-767]: https://yapp25app3.atlassian.net/browse/PC-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-767] Fix: 잘못된 navigationBar layout 수정

---

Presentation/Feature/Login/Sources/VerifingContact/VerifingContactView.swift

[PC-768](https://yapp25app3.atlassian.net/browse/PC-768)
- 회원가입 과정 중 전화번호 인증 화면에서 텍스트필드 외 화면을 눌렀을 경우와 확인 버튼을 눌렀을때 키보드가 내려가도록 수정
| 화면 이름 |
| :--: |
|  |
[PC-768]: https://yapp25app3.atlassian.net/browse/PC-768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-768] Fix: 텍스트 필드 외 배경 선택 시 키보드 내려가지 않는 문제 수정

---

Presentation/Feature/SignUp/Sources/TermsAgreement/TermsWebView.swift

[PC-771](https://yapp25app3.atlassian.net/browse/PC-771)
- 약관 웹뷰 네비게이션 레이아웃 수정 및 화면 전환
| 화면 이름 |
| :--: |
|  |
[PC-771]: https://yapp25app3.atlassian.net/browse/PC-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-771] Fix: 약관 웹뷰 네비게이션 레이아웃 수정 및 화면 전환

---

Presentation/DesignSystem/Sources/PCBottomSheet.swift
Presentation/Feature/EditProfile/Sources/EditProfileView.swift
Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift

[PC-772](https://yapp25app3.atlassian.net/browse/PC-772)
- 프로필 수정과 생성 시sns bottomsheet 높이 수정
-  PCBottomSheet에서 subtitle 변수 반영하지 않던 문제 해결
| 화면 이름 |
| :--: |
| ![image](https://github.com/user-attachments/assets/80065f82-b921-4e65-86b9-ecf49dfa771e) |
[PC-772]: https://yapp25app3.atlassian.net/browse/PC-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-772] Fix: sns bottomsheet 높이 수정 및 PCBottomSheet 수정

---

Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift

[PC-773](https://yapp25app3.atlassian.net/browse/PC-773)
- 작업 내용
- ㅇㅇㅇㅇ
| 화면 이름 |
| :--: |
|  |
[PC-773]: https://yapp25app3.atlassian.net/browse/PC-773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-773] Fix: 매칭 심사 카드 텍스트 크기 수정

---

Presentation/Feature/MatchingMain/Sources/MatchingTimer.swift

[PC-782](https://yapp25app3.atlassian.net/browse/PC-782)
- 작업 내용
- ㅇㅇㅇㅇ
| 화면 이름 |
| :--: |
|  |
[PC-782]: https://yapp25app3.atlassian.net/browse/PC-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-782] Fix: MatchingTimer 불필요한 패딩 값 제거

---

Presentation/Feature/EditProfile/Sources/EditProfileView.swift
Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift
Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift
Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift

[PC-785](https://yapp25app3.atlassian.net/browse/PC-785)
- QA에 따라 기타 선택 시, 생성되는 texteditor 삭제
| 화면 이름 |
| :--: |
|  |
[PC-785]: https://yapp25app3.atlassian.net/browse/PC-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-785] Fix: 지역 바텀 시트 기타 선택 시 texteditor 삭제

---

Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift
Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift

[PC-802](https://yapp25app3.atlassian.net/browse/PC-802)
- QA에 따라 지역 바텀 시트에서 선택지 중 기타 삭제
| 화면 이름 |
| :--: |
|  |
[PC-802]: https://yapp25app3.atlassian.net/browse/PC-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-802] Fix: 지역 선택지 중 기타 삭제

---

Data/DTO/Sources/Profile/ProfileBasicRequestDTO.swift
Domain/Entities/Sources/Profile/Jobs.swift
Domain/Entities/Sources/Profile/Locations.swift
Presentation/Feature/EditProfile/Sources/EditProfileView.swift
Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift
Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift

[PC-751](https://yapp25app3.atlassian.net/browse/PC-751)
- 작업 내용
- ㅇㅇㅇㅇ
| 화면 이름 |
| :--: |
|  |
[PC-751]: https://yapp25app3.atlassian.net/browse/PC-751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-751] Fix: 프로필 수정 시, 저장 버튼 예외 처리

---

Presentation/Feature/EditProfile/Sources/EditProfileView.swift
Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift

[PC-1008](https://yapp25app3.atlassian.net/browse/PC-1008)
- 작업 내용
- 히스토리 꼬임으로 인한 유실된 코드를 복구했습니다.
- PC-874의 파생 브랜치인 PC-982
- PC-874를 먼저 main에 머지한 이후, PC-982를 main에 머지하며 생긴 이슈
- revert하기 보다 수동으로 변경된 사항을 파악하여 해결하였습니다.
| 화면 이름 |
| :--: |
|  |
[PC-1008]: https://yapp25app3.atlassian.net/browse/PC-1008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-1008] Fix: 히스토리 꼬임으로 인한 유실된 코드 복구

---

App/Sources/PieceApp.swift

[PC-1150](https://yapp25app3.atlassian.net/browse/PC-1150)
- QA를 위해 주석을 달아 기능을 막았던 코드를 해제
| 화면 이름 |
| :--: |
|  |
[PC-1150]: https://yapp25app3.atlassian.net/browse/PC-1150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-1150] Fix: 캡처 방지 코드 주석 해제

---

Data/DTO/Sources/Matches/UserRejectReasonResponseDTO.swift
Domain/Entities/Sources/MatchMain/UserRejectReasonModel.swift
Presentation/DesignSystem/Sources/AlertView.swift
Presentation/DesignSystem/Sources/ViewModifiers/AlertModifier.swift
Presentation/Feature/EditProfile/Sources/EditProfileView.swift
Presentation/Feature/EditValuePick/Sources/EditValuePickView.swift
Presentation/Feature/EditValueTalk/Sources/EditValueTalkView.swift
Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift

[PC-1171](https://yapp25app3.atlassian.net/browse/PC-1171)
- 작업 내용
- 프로필 반려 시 알럿 구현
- 프로필 반려 알럿을 PCAlert로 사용할 수 있도록 확장
- 관련 DTO 수정
| 화면 이름 |
| :--: |
|  |
[PC-1171]: https://yapp25app3.atlassian.net/browse/PC-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PC-1171] Fix: 프로필 반려 시 알럿 구현
