Piece-iOS/Piece-iOS

Tuist/ProjectDescriptionHelpers/TemplateAttributeValue+default.swift, Tuist/Templates/feature/Project.stencil, Tuist/Templates/feature/View.stencil, Tuist/Templates/feature/ViewModel.stencil, Tuist/Templates/feature/feature.swift
[PC-62](https://yapp25app3.atlassian.net/browse/PC-62)
- `feature` 모듈 생성에 필요한 `Project.swift`, `View`, `ViewModel` 파일을 생성해주는 템플릿 구현
- 사용방법
1. 터미널에 `tuist scaffold feature --name {{ 피처이름 }}` 입력 시 해당 파일 생성
- 피처 이름은 Pascal case로 입력 (예: 매칭 메인 피처의 경우 `MatchingMain`)
2. `tuist edit` - `Tuist/Modules.swift` 파일에 해당 피처 추가
| 화면 이름 |
| :--: |
|  |
[PC-62]: https://yapp25app3.atlassian.net/browse/PC-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-62] Feat: feature 모듈을 생성하는 tuist 템플릿 구현

Presentation/DesignSystem/Resources/Icons.xcassets/photo-line-32.imageset/Contents.json, Presentation/DesignSystem/Resources/Icons.xcassets/photo-line-32.imageset/photo-line-32.svg, Presentation/DesignSystem/Sources/PCTabMini.swift, Presentation/DesignSystem/Sources/PCTextButton.swift, Presentation/DesignSystem/Sources/RoundedButton.swift, Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickAnswerModel.swift, Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickCard.swift, Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickModel.swift, Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickTab.swift, Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickView.swift, Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickViewModel.swift, Tuist/Templates/feature/View.stencil, Tuist/Templates/feature/ViewModel.stencil
[PC-196](https://yapp25app3.atlassian.net/browse/PC-196)
- 매칭 상세 가치관 Pick UI 구현
- `RoundedButton` 컴포넌트에 `rounding` 속성 추가
- `RoundedButton` 컴포넌트에 `.frame(maxWidth: .infinity)` 제거
- 버튼이 커져야 할 경우, 해당 컴포넌트를 사용하는 곳에서 `.frame(maxWidth: .infinity)`를 호출합니다.
- 뭔가 API 나오면 변경 사항이 좀 생길 거 같습니다... 서버에서 `나와 같은`/`나와 다른`을 어떻게 주느냐에 따라 달라질 것 같아요.
| 스크롤 X | 스크롤 시 | 최하단 스크롤 |
| :--: | :--: | :--: |
| ![image](https://github.com/user-attachments/assets/8cddba16-afc4-435a-a50e-fbbf59ff1d62) | ![image](https://github.com/user-attachments/assets/ef942649-6ad4-4c87-b9db-63a83baecd82) | ![image](https://github.com/user-attachments/assets/4d1e5fb0-f70e-4f43-b2e0-4d2f13b9bd5e) |
[PC-196]: https://yapp25app3.atlassian.net/browse/PC-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …
=> [PC-196] 매칭 상세 가치관 Pick UI 구현

Tuist/Package.resolved, Tuist/Package.swift, Tuist/ProjectDescriptionHelpers/AppEnvironment.swift, Tuist/ProjectDescriptionHelpers/Configuration/Configuration+configuration.swift, Tuist/ProjectDescriptionHelpers/Project/Project+app.swift, Tuist/ProjectDescriptionHelpers/Project/Project+dynamicFramework.swift, Tuist/ProjectDescriptionHelpers/Project/Project+dynamicResourceFramework.swift, Tuist/ProjectDescriptionHelpers/Project/Project+staticLibrary.swift, Tuist/ProjectDescriptionHelpers/Scheme/Scheme+makeScheme.swift, Tuist/ProjectDescriptionHelpers/Target/TargetDependency+SPM.swift
[PC-390](https://yapp25app3.atlassian.net/browse/PC-390)
- AS-IS: scheme을 `dev`/`prod`로 구분하여 빌드 환경(서버 API)를 분리하려 함
- `swift-navigation` 라이브러리를 사용하여 화면전환 처리를 하려고 하니 다음과 같은 tuist 오류 메시지 발생
```
· The project 'swift-case-paths' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [dev (debug), prod (release)]
· The project 'swift-concurrency-extras' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [dev (debug), prod (release)]
· The project 'xctest-dynamic-overlay' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [dev (debug), prod (release)]
· The project 'swift-custom-dump' has missing or mismatching configurations. It has …
```
=> [PC-390] Build: scheme을 dev/prod에서 debug/relesase로 수정

Presentation/Feature/SignUp/Project.swift, Presentation/Feature/SignUp/Sources/TermsAgreement/TermModel.swift, Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementView.swift, Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementViewModel.swift, Tuist/ProjectDescriptionHelpers/Modules.swift
[PC-391](https://yapp25app3.atlassian.net/browse/PC-391)
- Presentation > SignUp 모듈 생성
- 회원가입 중 약관동의 뷰 구현
| 화면 이름 |
| :--: |
| <img width="240" alt="image" src="https://github.com/user-attachments/assets/2ba14290-4d53-479e-9aad-f17794aaa627" /> |
[PC-391]: https://yapp25app3.atlassian.net/browse/PC-391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-391] Feat: 회원가입 중 약관동의 UI 구현

Presentation/Feature/SignUp/Sources/TermsAgreement/TermModel.swift, Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementView.swift, Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementViewModel.swift, Presentation/Feature/SignUp/Sources/TermsAgreement/TermsWebView.swift, Presentation/Feature/SignUp/Sources/TermsAgreement/TermsWebViewModel.swift, Presentation/Feature/SignUp/Sources/TermsAgreement/WebView.swift
[PC-392](https://yapp25app3.atlassian.net/browse/PC-392)
- **`WebView` 파일 생성** : UIViewRepresentable를 상속한 웹뷰는 url을 주입받아 해당 웹뷰를 띄웁니다.
- **`TermWebView`파일 생성** : `WebView`를 ZStack 레이어 가장 하단에 깔고, 그 위에 `nextButton`을 올렸습니다.
- **`TermModel`에 Hashable 프로토콜 추가** :  NavigationStack에서 처리할 데이터의 타입을 위해 추가했습니다.
- 하나의 PR에 너무 많은 내용이 있어 가독성이 떨어질까 생각해, 이전 PR 브랜치에서 따와 새 PR을 작성했습니다!
- 약관의 내용을 확인할 수 있는 상세 약관 웹뷰를 구현했습니다.
- 클로저를 사용해서 '동의하기' 버튼을 눌렀을 때, `TermsAgreementView`에 데이터가 반영되도록했습니다.
- `TermsAgreementView` Preview에서 아래 내용을 확인할 수 있습니다
-  [chevron 버튼을 눌러 해당하는 상세약관을 확인할 수 있다.]
-  [체크 버튼 + 텍스트 영역을 눌러 약관을 동의할 수 있다.]
-  [상세약관 웹뷰에서 동의하기 버튼을 누르면 이전뷰로 돌아간다. 이때 돌아온 뷰의 약관에 isChecked 속성이 반영된다.]
-  [모든 약관이 동의되어야만 다음 버튼이 활성화된다]
| TermsAgreementView -> TermWebView |
| :--: |
| <img width=375 alt="TermsAgreementView -> …
=> [PC-392] Feat: 약관 상세 웹뷰 UI 구현

App/Sources/ContentView.swift, Presentation/Coordinator/Project.swift, Presentation/Coordinator/Sources/Coordinator.swift, Presentation/DesignSystem/Sources/TabBarView.swift, Presentation/Feature/Home/Project.swift, Presentation/Feature/Home/Sources/HomeView.swift, Presentation/Feature/Home/Sources/HomeViewFactory.swift, Presentation/Feature/Home/Sources/HomeViewModel.swift, Presentation/Router/Sources/Route.swift, Tuist/ProjectDescriptionHelpers/Modules.swift
[PC-447](https://yapp25app3.atlassian.net/browse/PC-447)
- 홈 화면의 탭을 담는 Container 역할을 하는 화면 구현
- 개발상의 편의를 위해 앱 실행 시 홈 화면으로 라우팅 되도록 앱 모듈의 `ContentView` 수정
- 추후 `Splash` 화면 개발 시, `Splash`에서 `Onboarding` 또는 `Home`으로 분기 처리 로직 추가 예정
- `TabbarView`에서 `ObservableObject` 대신 `@Observable`을 사용하도록 변경
- `ObservableObject` 사용 시, `@Observable`을 사용하는 Feature에서 `ObservableObject`의 변경사항을 제대로 감지하지 못하는 이슈 발생
-
| 화면 이름 |
| :--: |
|  |
[PC-447]: https://yapp25app3.atlassian.net/browse/PC-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-447] Feat: 앱 홈 화면 구현

Presentation/DesignSystem/Sources/AlertView.swift, Presentation/DesignSystem/Sources/Dimmer.swift, Presentation/DesignSystem/Sources/RoundedButton.swift, Presentation/DesignSystem/Sources/ViewModifiers/AlertModifier.swift, Presentation/Feature/MatchingDetail/Sources/Common/MatchDetailPhotoView.swift
[PC-199](https://yapp25app3.atlassian.net/browse/PC-199)
- 매칭 상세 - 프로필 사진 화면 구현
- 서우님이 만들어주신 `AlertView`를 사용하기 위한 `pcAlert` modifier 구현
- `RoundedButton` 컴포넌트에서 너비값을 받을 수 있도록 수정
- 
| 매칭 상세 - 사진 |
| :--: |
| ![image](https://github.com/user-attachments/assets/2d6aad91-f661-4416-b229-7ddc0a71927f) |
[PC-199]: https://yapp25app3.atlassian.net/browse/PC-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-199] 매칭 상세 - 프로필 사진 화면 구현, alert modifier 구현

App/Project.swift, App/Sources/PieceApp.swift, Presentation/DesignSystem/Sources/ViewModifiers/ScreenshotPreventionModifier.swift, Presentation/Feature/Profile/Sources/ProfileView.swift
[PC-504](https://yapp25app3.atlassian.net/browse/PC-504)
- 스크린샷 방지 기능 도입
- 메인의 `Profile` 화면에 배경 흰색이 깔려있지 않던 문제 수정
- App의 최상단 `ContentView`에 적용되어 있어서 화면별로 추가로 적용하실 필요는 없습니다! @agseou 
| 화면 이름 |
| :--: |
|  |
[PC-504]: https://yapp25app3.atlassian.net/browse/PC-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-504] Feat: 스크린샷 방지 기능 도입

Data/LocalStorage/Sources/UserDefaults/PCUserDefaultsService.swift, Data/LocalStorage/Sources/UserDefaults/UserDefaultsKeys.swift, Presentation/Feature/Home/Project.swift, Presentation/Feature/Home/Sources/HomeView.swift, Presentation/Feature/Home/Sources/HomeViewModel.swift, Presentation/Feature/Home/Sources/TabBarButton.swift, Presentation/Feature/Home/Sources/TabBarView.swift, Presentation/Feature/Home/Sources/TabBarViewModel.swift, Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkCardViewModel.swift, Presentation/Feature/Splash/Sources/SplashViewModel.swift
[PC-674](https://yapp25app3.atlassian.net/browse/PC-674)
[PC-681](https://yapp25app3.atlassian.net/browse/PC-681)
- role이 USER가 아닌 사용자는 홈 화면의 탭에서 Profile에 진입할 수 없도록 수정
- `TabBarView`를 `Home` 모듈로 이동
- 홈 화면에 종속적인 로직을 처리하는 뷰여서 이동함
- 홈 화면에서 기본 내비게이션바 제거
- 
| 화면 이름 |
| :--: |
|  |
[PC-674]: https://yapp25app3.atlassian.net/browse/PC-674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PC-681]: https://yapp25app3.atlassian.net/browse/PC-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-675] Feat: role이 USER가 아닌 사용자는 프로필 탭에 진입할 수 없다

Presentation/DesignSystem/Sources/NavigationBar/NavigationBar.swift, Presentation/Feature/SignUp/Sources/AvoidContactsGuide/AvoidContactsGuideView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerViewModel.swift
[PC-705](https://yapp25app3.atlassian.net/browse/PC-705)
- 프로필 생성 버튼을 눌렀을 때 서버로부터 받은 빈 가치관Talk으로 가치관Talk을 다시 업데이트 하고 있어서 발생
- 이외 디자인가이드와 맞지 않는 UI 수정
- 
| 화면 이름 |
| :--: |
|  |
=> [PC-705] Fix: 프로필 생성 시 가치관Talk 답변이 비어있는 문제 수정

Data/DTO/Sources/Profile/ProfileBasicResponseDTO.swift, Presentation/Feature/EditProfile/Sources/EditProfileView.swift, Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift, Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift, Utility/PCFoundationExtension/Sources/String+Extension.swift
[PC-745](https://yapp25app3.atlassian.net/browse/PC-745)
- ProfileBasicResponseDTO에서 birthdate를 받아올 때, extractYear을 중복으로 쓰여 DTO에서 제거했습니다.
- 프로필 생성, 수정 시 텍스트 필드 정규식 적용해 잘못된 값 입력 방지
- 연락처 영어, 숫자, 특수문자만 입력되도록
-  키,몸무게 2~3자 제한
| 화면 이름 | 화면 이름 |
| ![image](https://github.com/user-attachments/assets/4ee4df8e-b005-46b1-8959-eac7de74c508) | ![image](https://github.com/user-attachments/assets/de3dbeac-8f52-4cde-a54c-1453044e260b) |
[PC-745]: https://yapp25app3.atlassian.net/browse/PC-745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-745] Fix: 프로필 생성, 수정 화면 텍스트필드 정규식 적용

Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift, Presentation/Feature/MatchingMain/Sources/MatchingTimer.swift
[PC-780](https://yapp25app3.atlassian.net/browse/PC-780)
- 매칭 nodata 상태에서 카드 상단 타이머 앞 텍스트 변경
- MathcinTimer에 prefixMessage 변수 추가
- 지영님 꼼꼼하십니다!! 짱짱!!!!!!!!
| AS-IS | TO-BE |
|![Simulator Screenshot - iPhone 16 Pro - 2025-03-24 at 14 34 50](https://github.com/user-attachments/assets/088b5361-ba3e-450b-8272-58d6cf616be7) | ![image](https://github.com/user-attachments/assets/705b9ad0-6394-49f0-84e0-30d005f577e8) |
[PC-780]: https://yapp25app3.atlassian.net/browse/PC-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-780] Fix: 매칭 Nodata 상태 시 카드 상단 타이머 앞 텍스트 수정

Data/DTO/Sources/Matches/MatchInfosResponseDTO.swift, Domain/Entities/Sources/MatchMain/MatchInfosModel.swift, Domain/Entities/Sources/MatchMain/MatchStatus.swift, Domain/RepositoryInterfaces/Sources/Settings/SettingsRepositoryInterface.swift, Presentation/Feature/MatchingMain/Sources/MatchingAnswer.swift, Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
[PC-748](https://yapp25app3.atlassian.net/browse/PC-748)
- AS-IS: 화면에 접근할 때마다, 조건 없이 유저의 리젝 사유를 받는 api를 호출
- TO-BE: userinfo를 내려주는 api에서 profileStatus를 가져온다. profileStatus가 REJECTED일 경우에만 api 호출
- MatchStatus enum을 통해 여러 곳에서 중복되어 사용되는 상태값(매칭 전, 대기중 ,수락, 매칭완료, 그린라이트) 통일
| 화면 이름 |
| :--: |
|  |
[PC-748]: https://yapp25app3.atlassian.net/browse/PC-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-748] Fix: Matching main 화면 접근 시, 프로필 리젝 로직 수정

Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
[PC-800](https://yapp25app3.atlassian.net/browse/PC-800)
- 매칭 메인 진입 시마다 match info API 호출하도록 변경
| 화면 이름 |
| :--: |
|  |
[PC-800]: https://yapp25app3.atlassian.net/browse/PC-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-800] Fix: 매칭 수락 후, 매칭 메인(홈) 진입 시 갱신 안되는 현상 수정

Presentation/DesignSystem/Sources/PCContactField.swift, Presentation/Feature/EditProfile/Sources/EditProfileView.swift, Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift
[PC-912](https://yapp25app3.atlassian.net/browse/PC-912)
프로필 생성/수정 화면의 연락처 필드 기능 전반을 개선하고 재사용 가능한 디자인 시스템 컴포넌트로 분리하였습니다.
- `PCContactField` 컴포넌트 추가
- 기존 작업자분이 만드신`PCTextEditor`를 사용하는 UI의 경우 연락처 타입에 따라 요구되는 UI를 구현할 수 없었습니다.
- 도메인 모델인 `ContactModel` 대신 `ContactDisplayModel`을 사용하여 `DesignSystem`에 정의
- `ContactDisplayModel`에 따라 `TextField` / `TextEditor`를 분기 처리하는 `ContactContainer` 추가
- `.openKakao` 타입만 `TextEditor`이며 동적 높이 지원
- 연락처 필드의 포커싱 및 키보드 버그 개선
- 연락처 추가/수정 시 자동 스크롤 및 포커싱 동작 처리
- 배경 터치 시 키보드 해제 로직 추가
1.  최대한 기존 코드는 건드리지 않고 UI 쪽만 수정해서 이슈를 해결해 보았습니다...
2. 
- 아래 버그가 있어서 `PCConactField`내부 `TextEditor`에서는 `.pretendard()`를 사용하지 않고 `.font()`를 사용했습니다. 
- 동적으로 높이 변경 시에 lineSpacing 때문에 아래처럼 내부 text가 empty일때랑 아닐때에 따라서 높이가 알아서 바뀌네요 ㅠㅠ
- 우선.. pretendard를 수정할 필요는 없을 것 같고 TextEditor같은 예외사항에 대해서만 조심하면 …
=> [PC-912] Fix: 프로필(생성/수정) 화면의 연락처 타입에 따라 서로 다른 연락처 필드를 구성하도록 변경

Domain/Entities/Sources/Profile/ContactModel.swift, Presentation/DesignSystem/Sources/PCBottomSheet.swift, Presentation/Feature/EditProfile/Sources/EditProfileView.swift, Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift
[PC-911](https://yapp25app3.atlassian.net/browse/PC-911)
- `PCBottomSheet` 구조 개선
- `PCBottomSheetItemRepresentable` 프로토콜을 정의했습니다.
- `id`, `text`, `state`, `render()`를 포함합니다.
- 위 프로토콜을 채택하는 `BottomSheetIconItem`과 `BottomSheetTextItem` 배열을 `PCBottomSheet` 인스턴스에 **Only 전달**만 하면 **피그마 바텀시트 디자인 요구사항에 맞는 모든 바텀시트 UI를 구현**할 수 있습니다.
- 기존 바텀시트의 화면전환 시 `.sheet()` 모디파이어를 사용하지 않는 구조를 개선하여 애니메이션과 함께 화면이 전환됩니다.
- PCBottomSheet를 개선한 이유
- 기존 PCBottomSheet는 이스케이핑 클로저를 통해서 내부 컨텐츠를 구현하여 전달하는 구조였습니다.
- 이 경우에 내부 `PCBottomSheet`에서 편집 중 상태관리가 어려웠고, 이를 구현하기 위해서는 바텀시트가 많은 `EditProfileView`와 `CreateBasicInfoView`에서 더욱 하드 코딩을 통한 1000줄 이상이 예상되어 `PCBottomSheet` 구조를 개선했습니다.
- ContactModel 프로퍼티 추가
- 프로필 변경/생성의 ViewModel 내부 Contact와의 매핑을 위한 Sugar를 추가했습니다. (다른 영향은 미치지 않습니다.)
| BottomSheetIconItem | BottomSheetTextItem |
| …
=> [PC-911] Fix: 연락처 추가 시 연락처가 유일하게 추가된다

Presentation/Feature/EditProfile/Sources/EditProfileView.swift, Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift
[PC-947](https://yapp25app3.atlassian.net/browse/PC-947)
- 작업 내용
- `Location`, `Job`의 바텀시트 ViewModel 로직 구현 및 UI 연동
- 필요 없는 코드 및 여백 삭제
- 일부 변수명 수정
- `isSNSSheetPresented` -> `isContactSheetPresented`
- https://github.com/Piece-iOS/Piece-iOS/pull/160 의 후속 PR입니다.
- iOS QA 사항이 많은것 같아 일단 빠르게 끝내고 다음 작업 이어해보도록 하겠습니당,,
- **Job의 경우 "기타" 탭 시 텍스트필드가 보여지는 기능 현재 미구현입니다.**
| Loctaion | Job |
| ![ㅁㄴㅇ](https://github.com/user-attachments/assets/3672100d-a8b7-43b8-abe9-158645a8f98d) |  ![ㅁㄴㅇ2](https://github.com/user-attachments/assets/302941e3-c62b-4d91-b94e-5217a666e137) |
[PC-947]: https://yapp25app3.atlassian.net/browse/PC-947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-947] Fix: 활동 지역과 직업을 각각 한 개씩 선택할 수 있다

Presentation/DesignSystem/Sources/PCBottomSheet.swift, Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift
[PC-948](https://yapp25app3.atlassian.net/browse/PC-948)
- `PCBottomSheet`에 커스텀 입력필드를 추가할 수 있도록 개선
- `BottomSheetItemType`을 추가하여 분기 처리
- `value`를 통해 Presenter와 커스텀 입력필드의 양방향 바인딩
- 우선 `BottomSheetTextItem`에만 커스텀 입력필드를 추가하도록 구현하였으며, 추후 `BottomSheetIconItem`에서 요구사항이 생길 시 구현 필요
```swift
public enum BottomSheetItemType {
case normal(String)
case custom(String)
}
public struct BottomSheetTextItem: BottomSheetItemRepresentable {
@Binding public var value: String
public var id: UUID
public var text: String
public var type: BottomSheetItemType
public var state: BottomSheetItemState = .unselected
...
}
```
- Job 바텀시트에 "기타" 입력 필드 추가
- 기타 옵션 선택 시(`.selected`) 텍스트 입력 필드 표시
- 입력 시 공백 자동 제거 기능 구현
- 바텀시트 아이템 선택 상태, 저장 로직 수정
- 선택 시 자동 스크롤 기능 개선
- `BottomSheetTextItem`를 (`.normal`, 또는 `.custom`) 타입으로 생성하여 …
=> [PC-948] Fix: 바텀시트에서 기타 선택 시 텍스트필드가 생긴다

Presentation/Feature/EditProfile/Sources/EditProfileView.swift, Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift
[PC-952](https://yapp25app3.atlassian.net/browse/PC-952)
- `setupJobItemsWithEtc()` 호출 시점을 `init`에서 `onAppear`로 이동
- `EditProfileViewModel` `Action`에 `.onAppear` 추가
- Binding 사용으로 인한 ViewModel 무한 init 문제 해결
- 기존 `setupJobItemsWithEtc()` 함수에서 `Binding`을 사용하여 `etcText`와 `BottomSheetTextItem`을 연결하고 있었습니다.
- `Binding`이 SwiftUI의 상태 관리 시스템과 직접적으로 연결되어 있어 ViewModel의 생명주기에 영향을 미치는 것으로 보였습니다.
- 이로 인해 ViewModel이 재생성될 때마다 `init`에서 `setupJobItemsWithEtc()`가 호출되고, 다시 ViewModel이 재생성되는 무한 루프 발생했습니다.
- `setupJobItemsWithEtc()` 호출을 `init`에서 `onAppear`로 이동했습니다.
- ViewModel의 초기화 시점과 상태 업데이트 시점을 분리하여 무한 루프 방지했습니다.
- 다만 자세한 원인을 모르겠습니다,, `init` 시점에 `etcText`가 변경되고 View가 업데이트 되면 @State인 ViewModel이 재생성되는 것의 무한 반복이었는데, `init` 시점이 아닐때는 `etcText`가 변경되어도 ViewModel이 재생성되는 일이 없습니다. 현재 해결방법은 …
=> [PC-952] Fix: EditProfile 화면 무한 API 호출 문제 해결

Presentation/Feature/Login/Sources/VerifingContact/VerifingContactView.swift, Presentation/Feature/Login/Sources/VerifingContact/VerifingContactViewModel.swift
[PC-978](https://yapp25app3.atlassian.net/browse/PC-978)
- 작업 내용
- 인증 완료 후 텍스트필드 및 버튼 disable 처리 및 timer 숨기기
- 기존 isActiveNextButton보다 직관적인 isPhoneVerificationCompleted로 네이밍 변경하여 사용
| 화면 이름 |
| :--: |
| ![Jun-04-2025 19-35-32](https://github.com/user-attachments/assets/463496f2-8f7a-4489-b052-8b62049b4e3a) |
[PC-978]: https://yapp25app3.atlassian.net/browse/PC-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-978] Fix: 인증완료 후 UI Disable 처리

Presentation/Feature/Login/Sources/VerifingContact/VerifingContactView.swift, Presentation/Feature/Login/Sources/VerifingContact/VerifingContactViewModel.swift, Utility/PCFoundationExtension/Sources/Double+Extension.swift
[PC-836](https://yapp25app3.atlassian.net/browse/PC-836)
- 작업 내용
- 백그라운드에서 타이머가 동작하는것처럼 `남은시간을 보정`하는 로직 구현
- 남은 시간 관련 변수 -> `timeRemaining`
- `ScenePhase`를 통한 `앱 생명주기 감지`
- **백그라운드에서 타이머 일시정지**
- **포어그라운드로 돌아올 때 백그라운드 시간만큼 타이머 시간 차감**
```swift
//  VerifingContactViewModel.swift
final class VerifingContactViewModel {
...
private var timeRemaining: TimeInterval = Constants.initialTime
private var isTimerRunning: Bool = false // 타이머 실행 상태 추적
private var backgroundTime: Date?
...
private func handleScenePhase(for scenePhase: ScenePhase) {
switch scenePhase {
case .background:
pauseTimerIfNeeded()
case .active:
resumeTimerIfNeeded()
default:
break
}
}
...
private func pauseTimerIfNeeded() {
// 타이머가 실행 중일 때만 처리
if isTimerRunning {
stopTimer()
backgroundTime = Date()
}
}
private func …
```
=> [PC-836] Fix: 백그라운드에서도 타이머가 동작하는 기능 구현

Presentation/Feature/Home/Sources/HomeViewModel.swift
[PC-932](https://yapp25app3.atlassian.net/browse/PC-932)
- 작업 내용
- HomeViewModel의 프로필 탭 접근제어 로직 개선
- 상위뷰인 HomeView에서 init 시점에 userRole이 정해짐.
- userRole을 UserDefaults에 저장하고 있으며, 이를 통해 프로필 탭 진입 여부를 판단하기 때문에 앱 삭제후 재설치 시 api 호출이 없는 상위뷰 init 시점에 UserRole을 판단하지 못함
- 따라서 하위 뷰인 MatchingMainView에서 getUserInfoUseCase 호출 이후에 상위 뷰에서 userRole이 업데이트가 안되는 이슈가 존재했음. 
- 상위뷰에서 UserRole을 연산 프로퍼티로 UserDefaults에서 참조하여 해결
| 앱 삭제 후에도 프로필 탭 접근 가능 |
| :--: |
| ![Jun-04-2025 20-28-45](https://github.com/user-attachments/assets/f26a53d3-9ca0-4597-b38c-5f84019a10d1) |
[PC-932]: https://yapp25app3.atlassian.net/browse/PC-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-980] Fix: 홈 화면에서 프로필 탭 접근 제어 로직 개선

Data/LocalStorage/Sources/UserDefaults/PCUserDefaultsService.swift, Data/PCNetwork/Sources/Endpoint/UserEndpoint.swift, Data/Repository/Sources/Login/LoginRepository.swift, Data/Repository/Sources/Profile/ProfileRepository.swift, Presentation/Feature/EditProfile/Sources/EditProfileView.swift, Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift, Presentation/Feature/Login/Project.swift, Presentation/Feature/Login/Sources/Login/LoginView.swift, Presentation/Feature/Login/Sources/Login/LoginViewModel.swift, Presentation/Feature/Login/Sources/VerifingContact/VerifingContactViewModel.swift, Presentation/Feature/Withdraw/Sources/WithdrawConfirm/WithdrawConfirmViewModel.swift, Tuist/Package.resolved, Tuist/Package.swift, Tuist/ProjectDescriptionHelpers/Project/Project+app.swift
[PC-932](https://yapp25app3.atlassian.net/browse/PC-932)
- 작업 내용
- GoogleSignIn SDK 의존성 추가를 위한 Project 파일 수정
- 기존 구글 간편로그인 UI 주석 해제
- 구글 간편로그인 로직 구현
- 구글 로그인한 경우 탈퇴 로직 구현
앱에서 기존 AccessToken을 저장하는 부분은 총 아래 3가지가 존재해야합니다.
`1. 소셜로그인 완료 시(NONE)`
`2. 전화번호 인증 완료 시(REGISTER) `
`3. 프로필생성 완료 시(심사이전) (PENDING) `
- 하지만 이전 1,2번에서만 토큰을 키체인에 저장하고 있었으며, 3번에는 키체인에 저장하는 로직이 없었습니다.
- 또한 이전 2,3 번에서는 `키체인 저장`과 별도로, request 헤더에 bearer 토큰을 추가하기 위한 `OAuthAuthenticator` 객체에 토큰을 업데이트하는 로직이 존재하지 않았습니다.
- 이로 인해 회원가입 및 프로필 생성 이후 홈 화면 진입 시 request 헤더에 전달되는 토큰의 상태는 `PENDING` 상태가 아닌 `NONE` 상태로 추가가 되었으며, 키체인에는 `REGISTER` 상태로 저장이 되고 있었습니다.
- 따라서, 가입 직후 바로 회원탈퇴 API 호출 시 `NONE` 상태의 토큰이 회원탈퇴 API 헤더에 추가되어 아래와 같은 `403 에러`가 발생했습니다.
(`NONE`의 경우 접근권한이 없기 때문에 deny됨, 정상적인 경우 회원가입 직후 token 복호화 시 role은 "3. `PENDING`" 이어야함)
```swift
🛰 …
```
=> [PC-932] Feat: 구글 간편 로그인 추가 및 회원 탈퇴 로직 개선

Data/DTO/Sources/User/UserInfoResponseDTO.swift, Data/Repository/Project.swift, Data/Repository/Sources/User/UserRepository.swift
[PC-1012](https://yapp25app3.atlassian.net/browse/PC-1012)
```swift
public struct UserInfoResponseDTO: Decodable {
public let userId: Int
public let role: String
public let profileStatus: ProfileStatus?
+ public let hasRoleChanged: Bool
+ public let accessToken: String?
+ public let refreshToken: String?
}
```
- `hasRoleChanged` -> 굳이 왜 줬는 지는 모르겠음?
- `accessToken`, `refreshToken` -> 갱신하면 됨
<br>
<br>
- 토큰 저장을 위한 `PCKeychainManager`에 접근하기 위함
<br>
<br>
```swift
final class UserRepository: UserRepositoryInterface {
...  
func getUserRole() async throws -> UserInfoModel {
let endpoint = UserEndpoint.getUserRole
let response: UserInfoResponseDTO = try await networkService.request(endpoint: endpoint)
+ updateTokensIfRoleChanged(response: response)
return response.toDomain()
}
}
+ private …
```
=> [PC-1012] Fix: UserInfo API 리스폰스 필드 변경 대응

Presentation/Feature/Settings/Sources/SettingsWebView.swift
[PC-1053](https://yapp25app3.atlassian.net/browse/PC-1053)
- 작업 내용
- 웹뷰 화면전환 시 네비게이션 바 숨김 처리
| 수정 전 | 수정 후
| <img width="316" height="662" alt="image" src="https://github.com/user-attachments/assets/7855bfbc-127b-4d97-81be-23ee725d7a0a" /> |  <img width="311" height="664" alt="image" src="https://github.com/user-attachments/assets/2ec0e820-b4e6-49ef-b0bf-04ebac497a37" /> |
[PC-1053]: https://yapp25app3.atlassian.net/browse/PC-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1053] Fix: 웹뷰 화면전환 시 네비게이션 바 숨김 처리

Presentation/Feature/EditValuePick/Sources/EditValuePickCard.swift, Presentation/Feature/EditValuePick/Sources/EditValuePickCardModel.swift, Presentation/Feature/EditValuePick/Sources/EditValuePickView.swift, Presentation/Feature/EditValuePick/Sources/EditValuePickViewModel.swift, Presentation/Feature/EditValueTalk/Sources/EditValueTalkView.swift, Presentation/Feature/EditValueTalk/Sources/EditValueTalkViewModel.swift
[PC-1024](https://yapp25app3.atlassian.net/browse/PC-1024)
- 작업 내용
- EditValuePick의 수정 및 저장 관련 미구현 된 부분 완료
- EditValuePick, EditValueTalk에 수정 중 화면 이탈 시 알럿 구현
- EditValueTalk에 AI 요약 부분 수정 및 저장이 정상 동작 하지 않는 것 같아 추가 구현이 필요해 보입니다.
- 이외 Jira에 ValueTalk 관련 `2차 오프라인 QA`에 추가 이슈가 존재합니다.
| EditValuePick | EditValueTalk |
| ![edtc](https://github.com/user-attachments/assets/d198eded-a0bc-4146-aba4-e7b471c139a8) |  ![edta](https://github.com/user-attachments/assets/5c77bfee-bddb-4502-8101-f166dc006748) |
[PC-1024]: https://yapp25app3.atlassian.net/browse/PC-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1024] Feat: 매칭 조각 화면 이탈 시 알럿 구현

Presentation/DesignSystem/Sources/AlertView.swift, Presentation/Feature/BlockUser/Sources/BlockUserView.swift, Presentation/Feature/EditProfile/Sources/EditProfileView.swift, Presentation/Feature/EditValuePick/Sources/EditValuePickView.swift, Presentation/Feature/EditValueTalk/Sources/EditValueTalkView.swift, Presentation/Feature/Home/Sources/HomeView.swift, Presentation/Feature/Login/Sources/Login/LoginView.swift, Presentation/Feature/MatchResult/Sources/MatchResultView.swift, Presentation/Feature/MatchingDetail/Sources/Common/MatchDetailPhotoView.swift, Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/MatchProfileBasicViewModel.swift, Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickView.swift, Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift, Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift, Presentation/Feature/Profile/Sources/ProfileView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickView.swift, Presentation/Feature/Withdraw/Sources/WithdrawConfirm/WithdrawConfirmView.swift, Presentation/Feature/Withdraw/Sources/WithdrawView.swift
[PC-1052](https://yapp25app3.atlassian.net/browse/PC-1052)
- 작업 내용
- 상호 매칭 수락 후 이어지는 화면의 네비게이션 바가 중복되는 버그를 해결했습니다.
- 상호 매칭 수락 후 이어지는 화면의 상대 닉네임이 누락되는 버그를 해결했습니다.
- **바로 적용 가능한 UX Writing 수정 사항**을 **모두** 반영했습니다.
| 화면 이름 |
| :--: |
|  |
[PC-1052]: https://yapp25app3.atlassian.net/browse/PC-1052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1052] Fix: 매칭 결과 화면 이슈 해결 및 UX Writing 수정 반영

Domain/UseCases/Sources/Permission/RequestContactsPermissionUseCase.swift, Presentation/Feature/SignUp/Sources/AvoidContactsGuide/AvoidContactsGuideView.swift, Presentation/Feature/SignUp/Sources/AvoidContactsGuide/AvoidContactsGuideViewModel.swift, Presentation/Feature/SignUp/Sources/PermissionRequest/PermissionRequestViewModel.swift
[PC-1046](https://yapp25app3.atlassian.net/browse/PC-1046)
- 연락처 권한 유즈케이스를 알림 권한에 할당하는 버그가 저희 노티 버그랑 관련이 있을까요?
| 권한이 있을 때 | 권한이 거부된 상태 |
| ![Jul-25-2025 21-23-31](https://github.com/user-attachments/assets/394227b9-3285-4ae5-b2f2-57112182c856) | ![Jul-25-2025 21-24-26](https://github.com/user-attachments/assets/bbc77e9a-f61a-4b9e-9c0c-5d967a534088) |
[PC-1046]: https://yapp25app3.atlassian.net/browse/PC-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1046] Fix: 가입 시 연락처 권한 관련 버그를 수정합니다.

Data/DTO/Sources/Matches/MatchInfosResponseDTO.swift, Domain/Entities/Sources/MatchMain/MatchInfosModel.swift, Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
[PC-1051](https://yapp25app3.atlassian.net/browse/PC-1051)
- 관련 DTO에 누락되어있던`blocked`를 추가했습니다.
- 매칭된 유저를 차단한 경우 홈 화면에서 해당 유저가 보이지 않도록 수정했습니다.
- 매칭-차단 플로우에서 매칭 상대 차단 시, 홈 화면으로 이동하며 아래 스크린샷과 같은 결과를 보여줍니다.
- 추후 다중 매칭이 가능해지면 전부 갈아 엎어야 될 것 같아서 너무 슬프네요
- 차단, 차단 해제, 매칭 등등 권한이 없어서 API 테스트가 굉장히 불편하네요..
| 매칭된 상태의 유저가 존재하지만 `blocked`가 `true`인 경우 pending 화면을 보여준다 |
| :--: |
| <img width="935" height="690" alt="image" src="https://github.com/user-attachments/assets/deccc54e-4dda-4265-907d-ef0b7ef113f2" /> |
[PC-1051]: https://yapp25app3.atlassian.net/browse/PC-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1051] Fix: 차단된 상태의 유저가 매칭에 보이지 않도록 수정

Presentation/DesignSystem/Sources/TextCountIndicator.swift, Presentation/Feature/EditValueTalk/Sources/EditValueTalkCard.swift, Presentation/Feature/EditValueTalk/Sources/EditValueTalkView.swift, Presentation/Feature/EditValueTalk/Sources/EditValueTalkViewModel.swift, Presentation/Feature/EditValueTalk/Sources/EditViewTalkCardViewModel.swift, Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerViewModel.swift, Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkCard.swift, Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkView.swift, Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkViewModel.swift
[PC-1048](https://yapp25app3.atlassian.net/browse/PC-1048)
- 작업 내용
- 가입/수정 시 ValueTalk의 TextEditor 작성 시 최소 글자 제한 관련 TextIndicator UI 구현
- 가입 시 ValueTalk 관련 ViewModel 버그 수정
- View 리렌더링 시 ViewModel이 초기화되는 버그를 수정
- 수정 시 ValueTalk의 isEdited 조건을 수정
- AI Summary가 다를 수 있기 때문
- 최소/최대 글자 제한 로직 추가
| 최소 글자 사용자 피드백 | 최소/최대 글자 제한 로직 추가 |
| ![Jul-28-2025 21-34-01](https://github.com/user-attachments/assets/1de50ca3-8dc4-4a8d-a033-75a326ab56e5) |  ![Jul-30-2025 20-44-21](https://github.com/user-attachments/assets/47a8587e-974f-466c-a7b7-d521076dfe04) |
[PC-1048]: https://yapp25app3.atlassian.net/browse/PC-1048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1048] Feature: ValueTalk의 최소 글자 제한 기능 추가

Tuist/ProjectDescriptionHelpers/AppContants.swift, Tuist/ProjectDescriptionHelpers/AppEnvironment.swift, Tuist/ProjectDescriptionHelpers/Configuration/Configuration+configuration.swift, Tuist/ProjectDescriptionHelpers/Project/Project+app.swift, Tuist/ProjectDescriptionHelpers/Scheme/Scheme+makeScheme.swift
- 민감한 정보는 config 파일로 관리
[PC-1072](https://yapp25app3.atlassian.net/browse/PC-1072)
- 작업 내용
- Tuist 설정을 통해 Debug/Release 스킴을 분리
- Debug/Config 파일을 통해 민감한 정보를 관리
- 추후 카카오디벨로퍼에서 멀티 BundleID 지원 시 운영/개발 앱의 타겟 분리가 가능할 것 같음.
- 지금은 불가능
| 화면 이름 |
| :--: |
|  |
[PC-1072]: https://yapp25app3.atlassian.net/browse/PC-1072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1072] Build: Debug/Release 스킴 분리

Data/DTO/Sources/Notification/NotificationType+Decodable.swift, Domain/Entities/Sources/Notification/NotificationType.swift, Presentation/Feature/NotificationList/Sources/NotificationItemModel.swift
[PC-1146](https://yapp25app3.atlassian.net/browse/PC-1146)
- PROFILE_IMAGE_APPROVED/REJECTED 알림 타입 지원
- 관련 NotificationType enum case 추가
- 관련 Model 변경 사항 추가
| 화면 이름 |
| :--: |
|  |
[PC-1146]: https://yapp25app3.atlassian.net/browse/PC-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1146] Feature: 프로필 재심사 푸쉬 알림 지원 추가

Presentation/Feature/ReportUser/Sources/ReportUserView.swift
[PC-1158](https://yapp25app3.atlassian.net/browse/PC-1158)
기타탭 누르고 키보드 한 번 올라가면 안내려감,
- 왼쪽 라디오버튼 1px 짤렸던 이슈 해결
- 포커싱 해제 안됐던 이슈 해결
- 키보드 올라오면 다음버튼 bottom padding 없는 이슈 해결
- 터치영역이 라디오 버튼영역밖에 안되던 이슈 해결
- 라디오버튼 Selected 상태에서 다시 누르면 Default 상태로 바뀌는 이슈 해결
- 텍스트필드 포커싱 상태에서 적절한 영역만큼 스크롤이 안되던 이슈 해결
- 신고버튼 누를 때 키보드 숨김처리가 안되는 이슈 해결
| 화면 이름 |
| :--: |
|  ![Aug-21-2025 22-34-53](https://github.com/user-attachments/assets/bbc4c9c6-a2dd-49d1-b4df-62acb0bbb530)  |
[PC-1158]: https://yapp25app3.atlassian.net/browse/PC-1158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1158] FIx: 신고 화면 버그 수정 및 UX/UI 개선

Presentation/Coordinator/Sources/Coordinator.swift, Presentation/Feature/SignUp/Sources/AvoidContactsGuide/AvoidContactsGuideView.swift, Presentation/Feature/SignUp/Sources/AvoidContactsGuide/AvoidContactsGuideViewModel.swift, Presentation/Feature/SignUp/Sources/PermissionRequest/PermissionRequestView.swift, Presentation/Feature/SignUp/Sources/PermissionRequest/PermissionRequestViewModel.swift, Presentation/Router/Sources/Route.swift
[PC-1201](https://yapp25app3.atlassian.net/browse/PC-1201)
- 작업 내용
- PermissionRequestView의 라우팅 플래그 초기화 이슈로 인해 백버튼으로 PermissionRequestView에 진입 시 "다음"버튼이 동작하지 않는 문제를 해결
- 일부 enum case 네이밍 컨벤션 적용
-  상태기반 라우팅을 통해 사용자 인터랙션 중복 방지
- 아는 사람 차단하기 화면에서 토스트가 나타나는 동안 사용자 인터랙션 방지
| 화면 이름 |
| :--: |
|  |
[PC-1201]: https://yapp25app3.atlassian.net/browse/PC-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1201] Fix: 아는 사람 차단하기 화면 라우팅 버그를 수정합니다.

App/Sources/AppDelegate.swift, Data/LocalStorage/Sources/Keychain/PCKeychain.swift, Data/Repository/Sources/Login/LoginRepository.swift, Presentation/Feature/Settings/Sources/SettingsViewModel.swift, Presentation/Feature/Splash/Sources/SplashViewModel.swift, Presentation/Feature/Withdraw/Sources/WithdrawConfirm/WithdrawConfirmViewModel.swift, Utility/PCFirebase/Project.swift, Utility/PCFirebase/Sources/PCNotificationService.swift, Utility/PCFoundationExtension/Sources/Notification.Name+.swift
[PC-1235](https://yapp25app3.atlassian.net/browse/PC-1235)
- 작업 내용
- 로그아웃/회원탈퇴 후 앱을 종료하지 않고 바로 로그인 시 서버에 FCM 토큰을 등록하지 못하는 문제 개선
- 최초 회원가입 및 로그인 시 AccessToken 없이 FCM 토큰을 서버에 등록할 수 없어 푸쉬 알림이 정상적으로 동작하지 않는 문제 개선
- PCFirebase의 FCM 토큰 등록 책임을 AppDelegate로 위임 및 책임 분리, 이로인한 불필요한 의존성 제거
| 화면 이름 |
| :--: |
|  |
[PC-1235]: https://yapp25app3.atlassian.net/browse/PC-1235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1235] Fix: FCM 토큰 등록/해제 관련 이슈 해결

Presentation/DesignSystem/Sources/PCContactField.swift
[PC-1240](https://yapp25app3.atlassian.net/browse/PC-1240)
- onAppear 시점에 메인 스레드로 바인딩 카피 및 재할당을 통해 레이아웃 계산을 트리거 활성화
- contact.value를 재할당하여 높이 변경 관련 UI 메인 런루프 유도
| Before |  After | 
| ![before](https://github.com/user-attachments/assets/629bd94f-24d9-4d65-b189-98723a8eecbf) |  ![after](https://github.com/user-attachments/assets/0392961c-08f2-4f46-b533-50dbd9cfe92f) |
[PC-1240]: https://yapp25app3.atlassian.net/browse/PC-1240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1240] Fix: TextEditor 초기 값에 맞게 동적 높이 반영 되지 않는 이슈 수정

App/Project.swift, App/Sources/PieceApp.swift, Presentation/Feature/MatchingMain/Project.swift, Tuist/Package.resolved, Tuist/ProjectDescriptionHelpers/ExternalDependencies.swift, Tuist/ProjectDescriptionHelpers/Project/Project+app.swift, Utility/PCAmplitude/Project.swift, Utility/PCFirebase/Project.swift, Utility/PCFirebase/Sources/PCFirebase.swift
[PC-752](https://yapp25app3.atlassian.net/browse/PC-752)
- 작업 내용
- Firebase Crashlytics 관련 의존성 추가 및 설정
- 아래와 같이배포시에만 수집하도록 제어
```swift
// PCFirebase.swift
private func setCrashlytics() {
#if DEBUG
Crashlytics.crashlytics().setCrashlyticsCollectionEnabled(false)
NSLog("🔥 Crashlytics disabled in DEBUG mode")
#else
Crashlytics.crashlytics().setCrashlyticsCollectionEnabled(true)
NSLog("🔥 Crashlytics enabled in RELEASE mode")
#endif
}
```
- 1.0.4 배포 예정
| Release 정상 작동 |
| :--: |
| <img width="1053" height="774" alt="image" src="https://github.com/user-attachments/assets/1cd03b53-7050-4d5b-8399-d5607f75cb84" /> |
[PC-752]: https://yapp25app3.atlassian.net/browse/PC-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-752] Feature: Firebase Crashlytics 세팅

App/Sources/ContentView.swift, Domain/Entities/Sources/Home/HomeViewTab.swift, Domain/Entities/Sources/Notification/NotificationType.swift, Presentation/Coordinator/Sources/Coordinator.swift, Presentation/Feature/Home/Sources/HomeView.swift, Presentation/Feature/Home/Sources/HomeViewFactory.swift, Presentation/Feature/Home/Sources/HomeViewModel.swift, Presentation/Router/Sources/Route.swift, Utility/PCFirebase/Sources/PCNotificationService.swift, Utility/PCFoundationExtension/Sources/Notification.Name+.swift
[PC-1151](https://yapp25app3.atlassian.net/browse/PC-1151)
- 작업 내용
- 서버 푸시의 NotificationType에 따라 Routing을 구현했습니다.
- 처리하는 페이로드 rawValue는 아래와 같습니다.
```swift
public extension NotificationType {
static func from(raw: String) -> NotificationType? {
switch raw {
case "PROFILE_APPROVED": return .profileApproved
case "PROFILE_REJECTED": return .profileRejected
case "PROFILE_IMAGE_APPROVED": return .profileImageApproved
case "PROFILE_IMAGE_REJECTED": return .profileImageRejected
case "MATCH_NEW": return .matchNew
case "MATCH_ACCEPTED": return .matchAccepted
case "MATCH_COMPLETED": return .matchCompleted
default: return nil
}
}
}
```
- PCFirebase에서는 의존성 순환을 막기위해 NotificationCenter를 통해 post를 보내어 이를 ContentView에서 파싱하여 DeepLink 처리하도록 구현하였습니다.
- PCNotificationService → NotificationCenter로 .deepLink …
=> [PC-1151] Feature: NotificationType 페이로드에 따른 APNs DeepLink Routing 처리

Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/MatchProfileBasicView.swift, Presentation/Feature/PreviewProfile/Sources/MatchProfileBasic/PreviewProfileBasicView.swift, Presentation/Feature/Profile/Sources/ProfileView.swift
[PC-1264](https://yapp25app3.atlassian.net/browse/PC-1264)
- 나이, 활동 지역 카드의 width 변경 (144->140)
- 해당 화면은 3가지입니다. (내 프로필, 가입 시 내 프로필 미리보기, 매칭 상대 프로필)
| 화면 이름 |
| :--: |
|  |
[PC-1264]: https://yapp25app3.atlassian.net/browse/PC-1264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-1264] Fix: 프로필 관련 UI 변경

App/Project.swift, App/Sources/ContentView.swift, App/Sources/PieceApp.swift, Tuist/ProjectDescriptionHelpers/Modules.swift, Utility/PCNetworkMonitor/Project.swift, Utility/PCNetworkMonitor/Sources/PCNetworkMonitor.swift
[PC-1286](https://yapp25app3.atlassian.net/browse/PC-1286)
- **네트워크 상태 감지**: 연결/끊어짐/인터페이스 변경 감지
- 연결: 
ex) Wi-Fi 연결, 셀룰러 데이터 연결, 비행기모드 해제
- 끊어짐: 
ex) Wi-Fi 끊어짐, 셀룰러 데이터 끊어짐, 비행기모드 활성화
- 인터페이스 변경:
ex) Wi-Fi ↔ LTE 전환, Wi-Fi 네트워크 변경, 셀룰러 변경
- **이벤트 방출**: `connected`, `disconnected`, `interfaceChanged` 이벤트
- 위 두 가지 외 내부 구현 캡슐화
```swift
/// 네트워크 이벤트 타입
public enum NetworkEvent: Equatable {
case connected
case disconnected
case interfaceChanged(from: [String], to: [String])
}
```
- **전역 상태 공유**: Environment를 통한 앱 전체 네트워크 상태 공유 기대
- **Utility/PCNetworkMonitor** 모듈 추가
- 최상위 AppRoot에서 PCNetworkMonitor를 의존하여 네트워크 상태 변화를 감지하여 에러 감지 및 활용 예정
| 네트워크 변경 시 예시 |
| :--: |
| <img width="751" height="260" alt="image" src="https://github.com/user-attachments/assets/2c4cd8a5-1434-43e9-9 …
=> [PC-1286] Feature: PCNetworkMonitor 모듈 구현
